spring:
  datasource:
    #数据源基本配置
    username: Zjf
    password: zjf123456
    url: jdbc:mysql://127.0.0.1:3306/mybatis?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

    #数据源其他配置
    maxActive: 20
    initialSize: 1
    maxWait: 600000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    maxPoolPreparedStatementPerConnectionSize: 500
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，’wall‘用于防火墙
    filters: stat，wall，log4j
mybatis:
  mapper‐locations: classpath:mybatis/mapper/*.xml #指定sql映射文件的位置
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.jc.springboot.dao.model

logging:
  level:
    com.jc.springboot.dao.mapper: debug
